exports.Admin = require('./admin.js');
exports.BashScript = require('./bashscript.js');
exports.Chmod = require('./chmod.js');
exports.Chown = require('./chown.js');
exports.Command = require('./command.js');          // LocalCommand, CreateRemoteCommand
exports.Compression = require('./compression.js');  // Zip, Tar
exports.Copy = require('./copy.js');  // TODO: make similar change in all imports
exports.Directory = require('./directory.js');
exports.DiskUsage = require('./diskusage.js');
exports.File = require('./file.js');
exports.Find = require('./find.js');
exports.List = require('./list.js');
exports.Mkdir = require('./mkdir.js');
exports.Move = require('./move.js');
exports.Path = require('./path.js');
exports.Permissions = require('./permissions.js');
exports.Ping = require('./ping.js');
exports.Remove = require('./remove.js');
exports.Rename = require('./rename.js');
exports.Rsync = require('./rsync.js');
exports.Timestamp = require('./timestamp.js');
exports.UserInfo = require('./userinfo.js');